// ARRAY de REPRESENTACIONES

const representaciones = [

    {
        imagen: "./img/representaciones/01_Besnes.jpg",
        titulo: "Vista de oeste de la ciudad de Montevideo sacada del mirador de la casa de Dn. Juan Ma. Perez.",
        tipo: "Acuarela y tinta sobre papel, 53 x 32cm",
        autor: "Juan Manuel Besnes e Irigoyen",
        nacionalidad: "Español",
        fecha: "1848",
        descripcion: "",
        fuente: "Museo Histórico Nacional, Uruguay",
    },
    {
        imagen: "./img/representaciones/01_Hastrel.jpeg",
        titulo: "",
        tipo: "Litografía sobre papel",
        autor: "Adolphe d'Hastrel de Rivedoux (1805-1874)",
        nacionalidad: "Francés",
        fecha: "",
        descripcion: "Vista de las azoteas y de la rada.",
        fuente: "Museo Nacional de Artes Visuales, Uruguay",
    },
    {
        imagen: "./img/representaciones/02_Hastrel.jpeg",
        titulo: "Vista de la Catedral desde las Azoteas",
        tipo: "Litografía sobre papel",
        autor: "Adolphe d'Hastrel de Rivedoux (1805-1874)",
        nacionalidad: "Francés",
        fecha: "",
        descripcion: "",
        fuente: "Museo Nacional de Artes Visuales, Uruguay",
    },
    {
        imagen: "./img/representaciones/01_cdf.png",
        titulo: "",
        tipo: "Fotografía. Gelatina y plata sobre vidrio",
        autor: "",
        nacionalidad: "",
        fecha: "1934",
        descripcion: "Dirigible Graf Zeppelin. A la derecha: Calle Santiago de Chile.",
        fuente: "CdF, Uruguay",
    },
    {
        imagen: "./img/representaciones/02_cdf.png",
        titulo: "",
        tipo: "Fotografía. Gelatina y plata sobre vidrio.",
        autor: "",
        nacionalidad: "",
        fecha: "1922-1923 aprox.",
        descripcion: "Barrios Centro y Aguada. Al fondo: Bahía de Montevideo.",
        fuente: "CdF, Uruguay",
    },
    {
        imagen: "./img/representaciones/03_cdf.png",
        titulo: "",
        tipo: "Fotografía. Gelatina y plata sobre plástico.",
        autor: "",
        nacionalidad: "",
        fecha: "1958",
        descripcion: "Barrio Cerro. Al fondo: Río de la Plata.",
        fuente: "CdF, Uruguay",
    },
    {
        imagen: "./img/representaciones/04_cdf.png",
        titulo: "",
        tipo: "Reproducción de copia fotográfica. Gelatina y plata sobre vidrio.",
        autor: "",
        nacionalidad: "",
        fecha: "1867",
        descripcion: "Calle Ibicuy y Plaza Cagancha.",
        fuente: "CdF, Uruguay",
    },

  ];
  
